#pragma once

#include <cstdint>

#define L16(XXX) (XXX << 16)

using sid_t = uint32_t;
using mid_t = uint32_t;
using cid_t = uint32_t;

enum IPC_TYPE_ID : uint32_t {
	IPC_TYPE_ID_START = 0X00001000,
	IPC_TYPE_ID_NUMBER,
	IPC_TYPE_ID_JSON,
	IPC_TYPE_ID_STRING,
	IPC_TYPE_ID_BINARY,
};

enum IPC_SERVER_ID : sid_t {
	IPC_SERVER_ID_START = 0X0000F000,
	IPC_SERVER_ID_HELLO,
	IPC_SERVER_ID_TEST1,
	IPC_SERVER_ID_TEST2,
};

enum IPC_MODULE_ID : mid_t {
	IPC_MODULE_ID_START = 0X0000E000,
	IPC_MODULE_ID_SYSTEM,
	IPC_MODULE_ID_TCP_SERVER,
	IPC_MODULE_ID_TCP_SESSION,
	IPC_MODULE_ID_TCP_CLIENT,
	IPC_MODULE_ID_LED,
	IPC_MODULE_ID_DATASOURCE,
	IPC_MODULE_ID_LIVESTREAM,
	IPC_MODULE_ID_HAHA,
	IPC_MODULE_ID_HEHE,
};

enum IPC_COMMAND_ID : cid_t {
	IPC_COMMAND_ID_START = L16(IPC_MODULE_ID_START),
	IPC_COMMAND_ID_STARTED,
	IPC_COMMAND_ID_PIPE = L16(IPC_MODULE_ID_SYSTEM),
	IPC_COMMAND_ID_PIPE_EXIT,
	IPC_COMMAND_ID_PIPE_LISTEN,
	IPC_COMMAND_ID_PIPE_UNLISTEN,
	IPC_COMMAND_ID_PIPE_SEND,

	IPC_COMMAND_ID_LED_ON = L16(IPC_MODULE_ID_LED),
	IPC_COMMAND_ID_LED_OFF,
	IPC_COMMAND_ID_LED_TRIGGER,

	IPC_COMMAND_ID_TCP_LISTEN = L16(IPC_MODULE_ID_TCP_SERVER),
	IPC_COMMAND_ID_TCP_UNLISTEN,
	IPC_COMMAND_ID_TCP_ADD_CLIENT,
	IPC_COMMAND_ID_TCP_DEL_CLIENT,
	IPC_COMMAND_ID_TCP_CONNECT,
	IPC_COMMAND_ID_TCP_DISCONNECT,
	IPC_COMMAND_ID_TCP_READ,
	IPC_COMMAND_ID_TCP_SEND,

	IPC_COMMAND_ID_DATASOURCE = L16(IPC_MODULE_ID_DATASOURCE),
	IPC_COMMAND_ID_NEW_DATASOURCE,
	IPC_COMMAND_ID_DEL_DATASOURCE,
	IPC_COMMAND_ID_FND_DATASOURCE,
	IPC_COMMAND_ID_START_DATASOURCE,
	IPC_COMMAND_ID_STOP_DATASOURCE,
	IPC_COMMAND_ID_UPDATE_FRAME,

	IPC_COMMAND_ID_HAHA = L16(IPC_MODULE_ID_HAHA),
	IPC_COMMAND_ID_HAHA_RESULT,
	IPC_COMMAND_ID_HAHA2,
	IPC_COMMAND_ID_HEHE = L16(IPC_MODULE_ID_HEHE),
};
